### ISSUE TITLE
Possible setting to also see the snapped pokemon

### ISSUE THREAD

**Issue by LivioNovak** [seanbelverstone/snaplocke-generator#23]
Why:
Together with a friend of mine we tried to bring that concept into a soul link, where the 2nd player has all the pokemon the 1st didn't get. But right now we have to meticulously time a screenshot to achieve that.

Idea:
make the option to show all the snapped pokemon in a 2nd, seperated list

**Comment by seanbelverstone** [comment]
Hi @LivioNovak, thank you for your great suggestion! I had an afternoon free and I've just pushed this implementation in. Make sure to give your browser a hard refresh and you should see the new option. Thanks for using the website! I hope this means you won't have to be a screenshot ninja in the future :)

![image](https://github.com/user-attachments/assets/f85b22c1-15c6-495b-9a0b-b1fafc86b2ff)
